# Generated by Django 5.0.6 on 2024-06-19 16:27

from django.db import migrations
from django.utils import timezone


def create_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    User.objects.create_user(username='user1_login', password='password1', is_active=True, date_joined=timezone.now())
    User.objects.create_user(username='user2_login', password='password2', is_active=True, date_joined=timezone.now())
    User.objects.create_user(username='user3_login', password='password3', is_active=True, date_joined=timezone.now())


class Migration(migrations.Migration):
    dependencies = [
        ('toDo', '0001_initial'),  # Update this to your actual latest migration file name if different
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
