# Generated by Django 5.0.6 on 2024-06-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0002_remove_old_task_time'),
        ('toDo', '0003_insert_users'),
    ]

    operations = [
    ]
